apiVersion: apps/v1
kind: Deployment
metadata:
  name: svg-to-pdf
  namespace: svg-to-pdf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svg-to-pdf
  template:
    metadata:
      labels:
        app: svg-to-pdf
    spec:
      containers:
        - name: svg-to-pdf
          image: fullpipe/svg-to-pdf:latest
          imagePullPolicy: Always
          env:
            - name: APP_ENV
              value: prod
            - name: APP_SECRET
              value: NfySmXw}6$)m}=bu*}3S(z#
---
apiVersion: v1
kind: Service
metadata:
  name: svg-to-pdf
  namespace: svg-to-pdf
spec:
  ports:
    - name: http
      targetPort: 80
      port: 80
  selector:
    app: svg-to-pdf
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: svg-to-pdf
  namespace: svg-to-pdf
spec:
  ingressClassName: 'traefik'
  tls:
    - hosts:
        - svg-to-pdf.fullpipe.dev
      secretName: svg-to-pdf.fullpipe.dev-tls
  rules:
    - host: svg-to-pdf.fullpipe.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: svg-to-pdf
                port:
                  name: http
